[package]
name = "fixed-multisig"
version.workspace = true
authors = ["Tushar Agrawal"]
edition = "2021"
description = "Implementing cw3 with an fixed group multisig"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cw-utils = { workspace = true }
cw2 = { workspace = true }
cw3 = { workspace = true }
cw-storage-plus = { workspace = true }
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
cw20 = { workspace = true }
cw20-base = { workspace = true }
cw-multi-test = { workspace = true }
easy-addr = { workspace = true }