[package]
name = "easy-addr"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
cosmwasm-std = "2.0.0"
proc-macro2 = "1"
quote = "1"
syn = { version = "1.0.6", features = ["full", "printing", "extra-traits"] }