[package]
name = "insurancePolicyIssuance"
version = "0.1.0"
edition = "2018"

[dependencies]
cosmwasm-std = "1.0.0"
cosmwasm-storage = "1.0.0"
cosmwasm-schema = "1.0.0"
cosmwasm-crypto = "1.0.0"
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cw2 = "0.10.0"
cw20 = "0.10.0"
cw721 = "0.10.0"
cw-storage-plus = "0.10.0"
thiserror = { version = "1.0.31" }


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[lib]
crate-type = ["cdylib", "rlib"]