[package]
name = "flex-multisig"
version = "2.0.0"
authors = ["Tushar Agrawal <developer.tusharagrawal@gmail.com>"]
edition = "2021"
description = "Implementing cw3 with multiple voting patterns and dynamic groups"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw3 = "2.0.0-rc.0"
cw3-fixed-multisig = {version = "2.0.0-rc.0", features = [
    "library",
] }
cw4 = "2.0.0-rc.0"
cw20 = "2.0.0-rc.0"


cosmwasm-schema = "2.0.0"
cosmwasm-std = "2.0.0"
cw2 = "2.0.0"
cw-controllers = "2.0.0"
cw-multi-test = "2.0.0"
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
schemars = "0.8.15"
semver = "1"
serde = { version = "1.0.188", default-features = false, features = ["derive"] }
thiserror = "1.0.4"

[dev-dependencies]
cw4-group = "2.0.0-rc.0"
cw-multi-test = "2.0.0"
cw20-base = { version = "2.0.0-rc.0", features = ["library"] }
